server:
  port: 9001
  tomcat:
#    TCP 연결 수락 후 실제 HTTP 요청을 받기까지 대기하는 시간
    connection-timeout: 2s
#    HTTP 요청을 기다리는 동안 연결을 유지하는 시간
    keep-alive-timeout: 15s
#    HTTP 요청을 처리하는 스레드 수
    threads:
      max: 50
#     최소 스레드 수
      min-spare: 5
      
